// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBsEE7WdPKTNMtmahRWd9Ir_keNixSOz6g",
    authDomain: "appionic-2ae06.firebaseapp.com",
    databaseURL: "https://appionic-2ae06-default-rtdb.firebaseio.com",
    projectId: "appionic-2ae06",
    storageBucket: "appionic-2ae06.appspot.com",
    messagingSenderId: "2005868271",
    appId: "1:2005868271:web:804912ddf77d89b64d851a",
    measurementId: "G-Q6N47BNDYZ"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBsEE7WdPKTNMtmahRWd9Ir_keNixSOz6g",
    authDomain: "appionic-2ae06.firebaseapp.com",
    databaseURL: "https://appionic-2ae06-default-rtdb.firebaseio.com",
    projectId: "appionic-2ae06",
    storageBucket: "appionic-2ae06.appspot.com",
    messagingSenderId: "2005868271",
    appId: "1:2005868271:web:804912ddf77d89b64d851a",
    measurementId: "G-Q6N47BNDYZ"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
  );
}